// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v6.31.1
// source: doorway.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "doorway";

export interface CreateDataRequest {
  name: string;
  email: string;
}

export interface Empty {
}

export interface Employee {
  id: number;
  name: string;
  email: string;
}

export interface DataResponse {
  message: string;
  data: Employee[];
}

export const DOORWAY_PACKAGE_NAME = "doorway";

function createBaseCreateDataRequest(): CreateDataRequest {
  return { name: "", email: "" };
}

export const CreateDataRequest: MessageFns<CreateDataRequest> = {
  encode(message: CreateDataRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.email !== "") {
      writer.uint32(18).string(message.email);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateDataRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateDataRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseEmpty(): Empty {
  return {};
}

export const Empty: MessageFns<Empty> = {
  encode(_: Empty, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Empty {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmpty();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseEmployee(): Employee {
  return { id: 0, name: "", email: "" };
}

export const Employee: MessageFns<Employee> = {
  encode(message: Employee, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.email !== "") {
      writer.uint32(26).string(message.email);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Employee {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmployee();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.email = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDataResponse(): DataResponse {
  return { message: "", data: [] };
}

export const DataResponse: MessageFns<DataResponse> = {
  encode(message: DataResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    for (const v of message.data) {
      Employee.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DataResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDataResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data.push(Employee.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface DoorwayServiceClient {
  getMessage(request: Empty): Observable<DataResponse>;

  createEmployee(request: CreateDataRequest): Observable<DataResponse>;
}

export interface DoorwayServiceController {
  getMessage(request: Empty): Promise<DataResponse> | Observable<DataResponse> | DataResponse;

  createEmployee(request: CreateDataRequest): Promise<DataResponse> | Observable<DataResponse> | DataResponse;
}

export function DoorwayServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getMessage", "createEmployee"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("DoorwayService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("DoorwayService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const DOORWAY_SERVICE_NAME = "DoorwayService";

export type DoorwayServiceService = typeof DoorwayServiceService;
export const DoorwayServiceService = {
  getMessage: {
    path: "/doorway.DoorwayService/GetMessage" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    requestDeserialize: (value: Buffer): Empty => Empty.decode(value),
    responseSerialize: (value: DataResponse): Buffer => Buffer.from(DataResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): DataResponse => DataResponse.decode(value),
  },
  createEmployee: {
    path: "/doorway.DoorwayService/CreateEmployee" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateDataRequest): Buffer => Buffer.from(CreateDataRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateDataRequest => CreateDataRequest.decode(value),
    responseSerialize: (value: DataResponse): Buffer => Buffer.from(DataResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): DataResponse => DataResponse.decode(value),
  },
} as const;

export interface DoorwayServiceServer extends UntypedServiceImplementation {
  getMessage: handleUnaryCall<Empty, DataResponse>;
  createEmployee: handleUnaryCall<CreateDataRequest, DataResponse>;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
